<?php
// Balíčky základních až mírně pokročilých slovíček, které jsou vhodná pro procvičování
// Vygenerováno umělou inteligencí

$starter_pack = [
    'en' => [
        ['cz' => 'Jablko', 'translation' => 'Apple', 'vyznam' => 'A round fruit with red or green skin.'],
        ['cz' => 'Hruška', 'translation' => 'Pear', 'vyznam' => 'A sweet fruit with a rounded base and a narrow top.'],
        ['cz' => 'Banán', 'translation' => 'Banana', 'vyznam' => 'A long curved fruit with yellow skin.'],
        ['cz' => 'Pomeranč', 'translation' => 'Orange', 'vyznam' => 'A round citrus fruit with orange skin.'],
        ['cz' => 'Citron', 'translation' => 'Lemon', 'vyznam' => 'A yellow citrus fruit with sour taste.'],
        ['cz' => 'Pes', 'translation' => 'Dog', 'vyznam' => 'A domesticated animal that often lives with people.'],
        ['cz' => 'Kočka', 'translation' => 'Cat', 'vyznam' => 'A small domesticated animal with soft fur.'],
        ['cz' => 'Pták', 'translation' => 'Bird', 'vyznam' => 'An animal with feathers that can usually fly.'],
        ['cz' => 'Ryba', 'translation' => 'Fish', 'vyznam' => 'An animal that lives in water and has fins.'],
        ['cz' => 'Králík', 'translation' => 'Rabbit', 'vyznam' => 'A small animal with long ears.'],

        ['cz' => 'Dům', 'translation' => 'House', 'vyznam' => 'A building for human habitation.'],
        ['cz' => 'Byt', 'translation' => 'Apartment', 'vyznam' => 'A set of rooms to live in, usually in a building.'],
        ['cz' => 'Pokoj', 'translation' => 'Room', 'vyznam' => 'A part of a building separated by walls.'],
        ['cz' => 'Kuchyně', 'translation' => 'Kitchen', 'vyznam' => 'A room where food is prepared.'],
        ['cz' => 'Koupelna', 'translation' => 'Bathroom', 'vyznam' => 'A room with a bath or shower.'],
        ['cz' => 'Ložnice', 'translation' => 'Bedroom', 'vyznam' => 'A room where people sleep.'],
        ['cz' => 'Obývák', 'translation' => 'Living room', 'vyznam' => 'A room for relaxing and spending time.'],
        ['cz' => 'Stůl', 'translation' => 'Table', 'vyznam' => 'A piece of furniture with a flat top and legs.'],
        ['cz' => 'Židle', 'translation' => 'Chair', 'vyznam' => 'A piece of furniture for sitting.'],
        ['cz' => 'Postel', 'translation' => 'Bed', 'vyznam' => 'A piece of furniture for sleeping.'],

        ['cz' => 'Kniha', 'translation' => 'Book', 'vyznam' => 'A set of written or printed pages bound together.'],
        ['cz' => 'Sešit', 'translation' => 'Notebook', 'vyznam' => 'A book of blank or ruled pages for writing.'],
        ['cz' => 'Pero', 'translation' => 'Pen', 'vyznam' => 'A tool used for writing with ink.'],
        ['cz' => 'Tužka', 'translation' => 'Pencil', 'vyznam' => 'A thin stick of graphite used for writing.'],
        ['cz' => 'Papír', 'translation' => 'Paper', 'vyznam' => 'Thin material used for writing and printing.'],
        ['cz' => 'Guma', 'translation' => 'Eraser', 'vyznam' => 'A small object used to remove pencil marks.'],
        ['cz' => 'Stůl', 'translation' => 'Desk', 'vyznam' => 'A table used for working or studying.'],
        ['cz' => 'Škola', 'translation' => 'School', 'vyznam' => 'A place where students learn.'],
        ['cz' => 'Učitel', 'translation' => 'Teacher', 'vyznam' => 'A person who teaches students.'],
        ['cz' => 'Student', 'translation' => 'Student', 'vyznam' => 'A person who studies at school.'],

        ['cz' => 'Auto', 'translation' => 'Car', 'vyznam' => 'A road vehicle with four wheels.'],
        ['cz' => 'Autobus', 'translation' => 'Bus', 'vyznam' => 'A large vehicle that carries many people.'],
        ['cz' => 'Vlak', 'translation' => 'Train', 'vyznam' => 'A long vehicle that runs on rails.'],
        ['cz' => 'Kolo', 'translation' => 'Bicycle', 'vyznam' => 'A vehicle with two wheels that you pedal.'],
        ['cz' => 'Letadlo', 'translation' => 'Airplane', 'vyznam' => 'A vehicle that flies in the sky.'],
        ['cz' => 'Loď', 'translation' => 'Boat', 'vyznam' => 'A vehicle that travels on water.'],
        ['cz' => 'Silnice', 'translation' => 'Road', 'vyznam' => 'A prepared surface for cars and other vehicles.'],
        ['cz' => 'Most', 'translation' => 'Bridge', 'vyznam' => 'A structure built to cross over something.'],
        ['cz' => 'Křižovatka', 'translation' => 'Crossroad', 'vyznam' => 'A place where roads meet.'],
        ['cz' => 'Semafor', 'translation' => 'Traffic light', 'vyznam' => 'A signal that controls traffic.'],

        ['cz' => 'Voda', 'translation' => 'Water', 'vyznam' => 'A clear liquid that people and animals drink.'],
        ['cz' => 'Vzduch', 'translation' => 'Air', 'vyznam' => 'The invisible gas we breathe.'],
        ['cz' => 'Oheň', 'translation' => 'Fire', 'vyznam' => 'Heat and light from burning.'],
        ['cz' => 'Země', 'translation' => 'Earth', 'vyznam' => 'The ground or the planet we live on.'],
        ['cz' => 'Strom', 'translation' => 'Tree', 'vyznam' => 'A tall plant with a trunk and branches.'],
        ['cz' => 'Květina', 'translation' => 'Flower', 'vyznam' => 'A colorful part of a plant.'],
        ['cz' => 'Tráva', 'translation' => 'Grass', 'vyznam' => 'Short green plants covering the ground.'],
        ['cz' => 'Řeka', 'translation' => 'River', 'vyznam' => 'A long, flowing body of water.'],
        ['cz' => 'Jezero', 'translation' => 'Lake', 'vyznam' => 'A large area of water surrounded by land.'],
        ['cz' => 'Moře', 'translation' => 'Sea', 'vyznam' => 'A large body of salty water.'],

        ['cz' => 'Den', 'translation' => 'Day', 'vyznam' => 'A period of twenty-four hours.'],
        ['cz' => 'Noc', 'translation' => 'Night', 'vyznam' => 'The time when it is dark outside.'],
        ['cz' => 'Ráno', 'translation' => 'Morning', 'vyznam' => 'The early part of the day.'],
        ['cz' => 'Odpoledne', 'translation' => 'Afternoon', 'vyznam' => 'The time after midday.'],
        ['cz' => 'Večer', 'translation' => 'Evening', 'vyznam' => 'The time between afternoon and night.'],
        ['cz' => 'Hodina', 'translation' => 'Hour', 'vyznam' => 'A period of sixty minutes.'],
        ['cz' => 'Minuta', 'translation' => 'Minute', 'vyznam' => 'A period of sixty seconds.'],
        ['cz' => 'Pondělí', 'translation' => 'Monday', 'vyznam' => 'The first day of the week for many people.'],
        ['cz' => 'Úterý', 'translation' => 'Tuesday', 'vyznam' => 'The second day of the week.'],
        ['cz' => 'Středa', 'translation' => 'Wednesday', 'vyznam' => 'The third day of the week.'],

        ['cz' => 'Čtvrtek', 'translation' => 'Thursday', 'vyznam' => 'The fourth day of the week.'],
        ['cz' => 'Pátek', 'translation' => 'Friday', 'vyznam' => 'The fifth day of the week.'],
        ['cz' => 'Sobota', 'translation' => 'Saturday', 'vyznam' => 'The sixth day of the week.'],
        ['cz' => 'Neděle', 'translation' => 'Sunday', 'vyznam' => 'The seventh day of the week.'],
        ['cz' => 'Muž', 'translation' => 'Man', 'vyznam' => 'An adult male person.'],
        ['cz' => 'Žena', 'translation' => 'Woman', 'vyznam' => 'An adult female person.'],
        ['cz' => 'Dítě', 'translation' => 'Child', 'vyznam' => 'A young person.'],
        ['cz' => 'Rodina', 'translation' => 'Family', 'vyznam' => 'Parents and their children together.'],
        ['cz' => 'Přítel', 'translation' => 'Friend', 'vyznam' => 'A person you like and spend time with.'],
        ['cz' => 'Doktor', 'translation' => 'Doctor', 'vyznam' => 'A person who treats sick people.'],

        ['cz' => 'Svoboda', 'translation' => 'Freedom', 'vyznam' => 'The state of being free from restrictions.'],
        ['cz' => 'Štěstí', 'translation' => 'Happiness', 'vyznam' => 'A feeling of great pleasure or joy.'],
        ['cz' => 'Smutek', 'translation' => 'Sadness', 'vyznam' => 'A feeling of unhappiness.'],
        ['cz' => 'Strach', 'translation' => 'Fear', 'vyznam' => 'An unpleasant emotion caused by danger.'],
        ['cz' => 'Naděje', 'translation' => 'Hope', 'vyznam' => 'A feeling of expectation for something good.'],
        ['cz' => 'Pravda', 'translation' => 'Truth', 'vyznam' => 'The quality of being true or factual.'],
        ['cz' => 'Lež', 'translation' => 'Lie', 'vyznam' => 'A false statement made on purpose.'],
        ['cz' => 'Vzpomínka', 'translation' => 'Memory', 'vyznam' => 'Something remembered from the past.'],
        ['cz' => 'Zkušenost', 'translation' => 'Experience', 'vyznam' => 'Knowledge gained through doing something.'],
        ['cz' => 'Důvěra', 'translation' => 'Trust', 'vyznam' => 'A firm belief in the reliability of someone.'],

        ['cz' => 'Vysvětlit', 'translation' => 'Explain', 'vyznam' => 'To make something clear or easy to understand.'],
        ['cz' => 'Souhlasit', 'translation' => 'Agree', 'vyznam' => 'To have the same opinion as someone else.'],
        ['cz' => 'Odmítnout', 'translation' => 'Refuse', 'vyznam' => 'To say no to something offered or requested.'],
        ['cz' => 'Překvapit', 'translation' => 'Surprise', 'vyznam' => 'To cause someone to feel unexpected wonder.'],
        ['cz' => 'Zapomenout', 'translation' => 'Forget', 'vyznam' => 'To fail to remember something.'],
        ['cz' => 'Rozhodnout', 'translation' => 'Decide', 'vyznam' => 'To make a choice after thinking about options.'],
        ['cz' => 'Porovnat', 'translation' => 'Compare', 'vyznam' => 'To examine similarities and differences.'],
        ['cz' => 'Představit', 'translation' => 'Introduce', 'vyznam' => 'To make someone known to another person.'],
        ['cz' => 'Dosáhnout', 'translation' => 'Achieve', 'vyznam' => 'To successfully reach a goal.'],
        ['cz' => 'Pochopit', 'translation' => 'Understand', 'vyznam' => 'To grasp the meaning of something.'],

        ['cz' => 'Nebezpečný', 'translation' => 'Dangerous', 'vyznam' => 'Likely to cause harm or injury.'],
        ['cz' => 'Užitečný', 'translation' => 'Useful', 'vyznam' => 'Able to be used for a practical purpose.'],
        ['cz' => 'Nemožný', 'translation' => 'Impossible', 'vyznam' => 'Not able to happen or be done.'],
        ['cz' => 'Spokojený', 'translation' => 'Satisfied', 'vyznam' => 'Feeling that expectations have been met.'],
        ['cz' => 'Zvědavý', 'translation' => 'Curious', 'vyznam' => 'Eager to know or learn something.'],
        ['cz' => 'Trpělivý', 'translation' => 'Patient', 'vyznam' => 'Able to wait calmly without complaining.'],
        ['cz' => 'Líný', 'translation' => 'Lazy', 'vyznam' => 'Unwilling to work or use energy.'],
        ['cz' => 'Hrdý', 'translation' => 'Proud', 'vyznam' => 'Feeling deep pleasure from achievements.'],
        ['cz' => 'Samostatný', 'translation' => 'Independent', 'vyznam' => 'Able to do things without help from others.'],
        ['cz' => 'Spravedlivý', 'translation' => 'Fair', 'vyznam' => 'Treating people equally and without bias.'],

        ['cz' => 'Společnost', 'translation' => 'Society', 'vyznam' => 'A group of people living together in a community.'],
        ['cz' => 'Vláda', 'translation' => 'Government', 'vyznam' => 'The group of people who rule a country.'],
        ['cz' => 'Zákon', 'translation' => 'Law', 'vyznam' => 'A rule made by the government.'],
        ['cz' => 'Volby', 'translation' => 'Election', 'vyznam' => 'A process of choosing leaders by voting.'],
        ['cz' => 'Občan', 'translation' => 'Citizen', 'vyznam' => 'A person who legally belongs to a country.'],

        ['cz' => 'Plat', 'translation' => 'Salary', 'vyznam' => 'Money paid regularly for work.'],
        ['cz' => 'Podnik', 'translation' => 'Business', 'vyznam' => 'An organization that sells goods or services.'],
        ['cz' => 'Smlouva', 'translation' => 'Contract', 'vyznam' => 'A written legal agreement between parties.'],
        ['cz' => 'Daň', 'translation' => 'Tax', 'vyznam' => 'Money paid to the government from income or purchases.'],
        ['cz' => 'Zaměstnanec', 'translation' => 'Employee', 'vyznam' => 'A person who works for a company.'],

        ['cz' => 'Výzkum', 'translation' => 'Research', 'vyznam' => 'A careful study to discover new facts.'],
        ['cz' => 'Přístroj', 'translation' => 'Device', 'vyznam' => 'A piece of equipment made for a specific purpose.'],
        ['cz' => 'Vynález', 'translation' => 'Invention', 'vyznam' => 'A new thing that someone has created.'],
        ['cz' => 'Údaj', 'translation' => 'Data', 'vyznam' => 'Facts and information collected for analysis.'],
        ['cz' => 'Hmota', 'translation' => 'Matter', 'vyznam' => 'Physical substance that occupies space.'],

        ['cz' => 'Nemoc', 'translation' => 'Disease', 'vyznam' => 'An illness that affects the body or mind.'],
        ['cz' => 'Lék', 'translation' => 'Medicine', 'vyznam' => 'A substance used to treat illness.'],
        ['cz' => 'Bolest', 'translation' => 'Pain', 'vyznam' => 'An unpleasant physical feeling caused by injury.'],
        ['cz' => 'Svaly', 'translation' => 'Muscles', 'vyznam' => 'Body tissues that produce movement.'],
        ['cz' => 'Dýchání', 'translation' => 'Breathing', 'vyznam' => 'The process of taking air in and out of lungs.'],
        ['cz' => 'Předpokládat', 'translation' => 'Assume', 'vyznam' => 'To accept something as true without proof.'],

    ],

    'de' => [
        ['cz' => 'Jablko', 'translation' => 'Apfel'],
        ['cz' => 'Hruška', 'translation' => 'Birne'],
        ['cz' => 'Banán', 'translation' => 'Banane'],
        ['cz' => 'Pomeranč', 'translation' => 'Orange'],
        ['cz' => 'Citron', 'translation' => 'Zitrone'],
        ['cz' => 'Pes', 'translation' => 'Hund'],
        ['cz' => 'Kočka', 'translation' => 'Katze'],
        ['cz' => 'Pták', 'translation' => 'Vogel'],
        ['cz' => 'Ryba', 'translation' => 'Fisch'],
        ['cz' => 'Králík', 'translation' => 'Kaninchen'],

        ['cz' => 'Dům', 'translation' => 'Haus'],
        ['cz' => 'Byt', 'translation' => 'Wohnung'],
        ['cz' => 'Pokoj', 'translation' => 'Zimmer'],
        ['cz' => 'Kuchyně', 'translation' => 'Küche'],
        ['cz' => 'Koupelna', 'translation' => 'Badezimmer'],
        ['cz' => 'Ložnice', 'translation' => 'Schlafzimmer'],
        ['cz' => 'Obývák', 'translation' => 'Wohnzimmer'],
        ['cz' => 'Stůl', 'translation' => 'Tisch'],
        ['cz' => 'Židle', 'translation' => 'Stuhl'],
        ['cz' => 'Postel', 'translation' => 'Bett'],

        ['cz' => 'Kniha', 'translation' => 'Buch'],
        ['cz' => 'Sešit', 'translation' => 'Heft'],
        ['cz' => 'Pero', 'translation' => 'Stift'],
        ['cz' => 'Tužka', 'translation' => 'Bleistift'],
        ['cz' => 'Papír', 'translation' => 'Papier'],
        ['cz' => 'Guma', 'translation' => 'Radiergummi'],
        ['cz' => 'Škola', 'translation' => 'Schule'],
        ['cz' => 'Učitel', 'translation' => 'Lehrer'],
        ['cz' => 'Student', 'translation' => 'Student'],
        ['cz' => 'Třída', 'translation' => 'Klasse'],

        ['cz' => 'Auto', 'translation' => 'Auto'],
        ['cz' => 'Autobus', 'translation' => 'Bus'],
        ['cz' => 'Vlak', 'translation' => 'Zug'],
        ['cz' => 'Kolo', 'translation' => 'Fahrrad'],
        ['cz' => 'Letadlo', 'translation' => 'Flugzeug'],
        ['cz' => 'Loď', 'translation' => 'Schiff'],
        ['cz' => 'Silnice', 'translation' => 'Straße'],
        ['cz' => 'Most', 'translation' => 'Brücke'],
        ['cz' => 'Křižovatka', 'translation' => 'Kreuzung'],
        ['cz' => 'Semafor', 'translation' => 'Ampel'],

        ['cz' => 'Voda', 'translation' => 'Wasser'],
        ['cz' => 'Vzduch', 'translation' => 'Luft'],
        ['cz' => 'Oheň', 'translation' => 'Feuer'],
        ['cz' => 'Země', 'translation' => 'Erde'],
        ['cz' => 'Strom', 'translation' => 'Baum'],
        ['cz' => 'Květina', 'translation' => 'Blume'],
        ['cz' => 'Tráva', 'translation' => 'Gras'],
        ['cz' => 'Řeka', 'translation' => 'Fluss'],
        ['cz' => 'Jezero', 'translation' => 'See'],
        ['cz' => 'Moře', 'translation' => 'Meer'],

        ['cz' => 'Den', 'translation' => 'Tag'],
        ['cz' => 'Noc', 'translation' => 'Nacht'],
        ['cz' => 'Ráno', 'translation' => 'Morgen'],
        ['cz' => 'Odpoledne', 'translation' => 'Nachmittag'],
        ['cz' => 'Večer', 'translation' => 'Abend'],
        ['cz' => 'Hodina', 'translation' => 'Stunde'],
        ['cz' => 'Minuta', 'translation' => 'Minute'],
        ['cz' => 'Pondělí', 'translation' => 'Montag'],
        ['cz' => 'Úterý', 'translation' => 'Dienstag'],
        ['cz' => 'Středa', 'translation' => 'Mittwoch'],

        ['cz' => 'Čtvrtek', 'translation' => 'Donnerstag'],
        ['cz' => 'Pátek', 'translation' => 'Freitag'],
        ['cz' => 'Sobota', 'translation' => 'Samstag'],
        ['cz' => 'Neděle', 'translation' => 'Sonntag'],
        ['cz' => 'Muž', 'translation' => 'Mann'],
        ['cz' => 'Žena', 'translation' => 'Frau'],
        ['cz' => 'Dítě', 'translation' => 'Kind'],
        ['cz' => 'Rodina', 'translation' => 'Familie'],
        ['cz' => 'Přítel', 'translation' => 'Freund'],
        ['cz' => 'Doktor', 'translation' => 'Arzt'],

         ['cz' => 'Svoboda', 'translation' => 'Freiheit'],
        ['cz' => 'Štěstí', 'translation' => 'Glück'],
        ['cz' => 'Smutek', 'translation' => 'Traurigkeit'],
        ['cz' => 'Strach', 'translation' => 'Angst'],
        ['cz' => 'Naděje', 'translation' => 'Hoffnung'],
        ['cz' => 'Pravda', 'translation' => 'Wahrheit'],
        ['cz' => 'Lež', 'translation' => 'Lüge'],
        ['cz' => 'Vzpomínka', 'translation' => 'Erinnerung'],
        ['cz' => 'Zkušenost', 'translation' => 'Erfahrung'],
        ['cz' => 'Důvěra', 'translation' => 'Vertrauen'],
        ['cz' => 'Vysvětlit', 'translation' => 'Erklären'],
        ['cz' => 'Souhlasit', 'translation' => 'Zustimmen'],
        ['cz' => 'Odmítnout', 'translation' => 'Ablehnen'],
        ['cz' => 'Překvapit', 'translation' => 'Überraschen'],
        ['cz' => 'Zapomenout', 'translation' => 'Vergessen'],
        ['cz' => 'Rozhodnout', 'translation' => 'Entscheiden'],
        ['cz' => 'Porovnat', 'translation' => 'Vergleichen'],
        ['cz' => 'Představit', 'translation' => 'Vorstellen'],
        ['cz' => 'Dosáhnout', 'translation' => 'Erreichen'],
        ['cz' => 'Pochopit', 'translation' => 'Verstehen'],
        ['cz' => 'Nebezpečný', 'translation' => 'Gefährlich'],
        ['cz' => 'Užitečný', 'translation' => 'Nützlich'],
        ['cz' => 'Nemožný', 'translation' => 'Unmöglich'],
        ['cz' => 'Spokojený', 'translation' => 'Zufrieden'],
        ['cz' => 'Zvědavý', 'translation' => 'Neugierig'],
        ['cz' => 'Trpělivý', 'translation' => 'Geduldig'],
        ['cz' => 'Líný', 'translation' => 'Faul'],
        ['cz' => 'Hrdý', 'translation' => 'Stolz'],
        ['cz' => 'Samostatný', 'translation' => 'Selbstständig'],
        ['cz' => 'Spravedlivý', 'translation' => 'Gerecht'],
        ['cz' => 'Společnost', 'translation' => 'Gesellschaft'],
        ['cz' => 'Vláda', 'translation' => 'Regierung'],
        ['cz' => 'Zákon', 'translation' => 'Gesetz'],
        ['cz' => 'Volby', 'translation' => 'Wahl'],
        ['cz' => 'Občan', 'translation' => 'Bürger'],
        ['cz' => 'Plat', 'translation' => 'Gehalt'],
        ['cz' => 'Podnik', 'translation' => 'Unternehmen'],
        ['cz' => 'Smlouva', 'translation' => 'Vertrag'],
        ['cz' => 'Daň', 'translation' => 'Steuer'],
        ['cz' => 'Zaměstnanec', 'translation' => 'Angestellter'],
        ['cz' => 'Výzkum', 'translation' => 'Forschung'],
        ['cz' => 'Přístroj', 'translation' => 'Gerät'],
        ['cz' => 'Vynález', 'translation' => 'Erfindung'],
        ['cz' => 'Údaj', 'translation' => 'Daten'],
        ['cz' => 'Hmota', 'translation' => 'Materie'],
        ['cz' => 'Nemoc', 'translation' => 'Krankheit'],
        ['cz' => 'Lék', 'translation' => 'Medikament'],
        ['cz' => 'Bolest', 'translation' => 'Schmerz'],
        ['cz' => 'Svaly', 'translation' => 'Muskeln'],
        ['cz' => 'Dýchání', 'translation' => 'Atmung'],
        ['cz' => 'Předpokládat', 'translation' => 'Annehmen'],
    ],

    'fr' => [
        ['cz' => 'Jablko', 'translation' => 'Pomme'],
        ['cz' => 'Hruška', 'translation' => 'Poire'],
        ['cz' => 'Banán', 'translation' => 'Banane'],
        ['cz' => 'Pomeranč', 'translation' => 'Orange'],
        ['cz' => 'Citron', 'translation' => 'Citron'],
        ['cz' => 'Pes', 'translation' => 'Chien'],
        ['cz' => 'Kočka', 'translation' => 'Chat'],
        ['cz' => 'Pták', 'translation' => 'Oiseau'],
        ['cz' => 'Ryba', 'translation' => 'Poisson'],
        ['cz' => 'Králík', 'translation' => 'Lapin'],

        ['cz' => 'Dům', 'translation' => 'Maison'],
        ['cz' => 'Byt', 'translation' => 'Appartement'],
        ['cz' => 'Pokoj', 'translation' => 'Chambre'],
        ['cz' => 'Kuchyně', 'translation' => 'Cuisine'],
        ['cz' => 'Koupelna', 'translation' => 'Salle de bains'],
        ['cz' => 'Ložnice', 'translation' => 'Chambre à coucher'],
        ['cz' => 'Obývák', 'translation' => 'Salon'],
        ['cz' => 'Stůl', 'translation' => 'Table'],
        ['cz' => 'Židle', 'translation' => 'Chaise'],
        ['cz' => 'Postel', 'translation' => 'Lit'],

        ['cz' => 'Kniha', 'translation' => 'Livre'],
        ['cz' => 'Sešit', 'translation' => 'Cahier'],
        ['cz' => 'Pero', 'translation' => 'Stylo'],
        ['cz' => 'Tužka', 'translation' => 'Crayon'],
        ['cz' => 'Papír', 'translation' => 'Papier'],
        ['cz' => 'Guma', 'translation' => 'Gomme'],
        ['cz' => 'Škola', 'translation' => 'École'],
        ['cz' => 'Učitel', 'translation' => 'Professeur'],
        ['cz' => 'Student', 'translation' => 'Étudiant'],
        ['cz' => 'Třída', 'translation' => 'Classe'],

        ['cz' => 'Auto', 'translation' => 'Voiture'],
        ['cz' => 'Autobus', 'translation' => 'Bus'],
        ['cz' => 'Vlak', 'translation' => 'Train'],
        ['cz' => 'Kolo', 'translation' => 'Vélo'],
        ['cz' => 'Letadlo', 'translation' => 'Avion'],
        ['cz' => 'Loď', 'translation' => 'Bateau'],
        ['cz' => 'Silnice', 'translation' => 'Route'],
        ['cz' => 'Most', 'translation' => 'Pont'],
        ['cz' => 'Křižovatka', 'translation' => 'Carrefour'],
        ['cz' => 'Semafor', 'translation' => 'Feu de circulation'],

        ['cz' => 'Voda', 'translation' => 'Eau'],
        ['cz' => 'Vzduch', 'translation' => 'Air'],
        ['cz' => 'Oheň', 'translation' => 'Feu'],
        ['cz' => 'Země', 'translation' => 'Terre'],
        ['cz' => 'Strom', 'translation' => 'Arbre'],
        ['cz' => 'Květina', 'translation' => 'Fleur'],
        ['cz' => 'Tráva', 'translation' => 'Herbe'],
        ['cz' => 'Řeka', 'translation' => 'Rivière'],
        ['cz' => 'Jezero', 'translation' => 'Lac'],
        ['cz' => 'Moře', 'translation' => 'Mer'],

        ['cz' => 'Den', 'translation' => 'Jour'],
        ['cz' => 'Noc', 'translation' => 'Nuit'],
        ['cz' => 'Ráno', 'translation' => 'Matin'],
        ['cz' => 'Odpoledne', 'translation' => 'Après-midi'],
        ['cz' => 'Večer', 'translation' => 'Soir'],
        ['cz' => 'Hodina', 'translation' => 'Heure'],
        ['cz' => 'Minuta', 'translation' => 'Minute'],
        ['cz' => 'Pondělí', 'translation' => 'Lundi'],
        ['cz' => 'Úterý', 'translation' => 'Mardi'],
        ['cz' => 'Středa', 'translation' => 'Mercredi'],

        ['cz' => 'Čtvrtek', 'translation' => 'Jeudi'],
        ['cz' => 'Pátek', 'translation' => 'Vendredi'],
        ['cz' => 'Sobota', 'translation' => 'Samedi'],
        ['cz' => 'Neděle', 'translation' => 'Dimanche'],
        ['cz' => 'Muž', 'translation' => 'Homme'],
        ['cz' => 'Žena', 'translation' => 'Femme'],
        ['cz' => 'Dítě', 'translation' => 'Enfant'],
        ['cz' => 'Rodina', 'translation' => 'Famille'],
        ['cz' => 'Přítel', 'translation' => 'Ami'],
        ['cz' => 'Doktor', 'translation' => 'Docteur'],

        ['cz' => 'Svoboda', 'translation' => 'Liberté'],
        ['cz' => 'Štěstí', 'translation' => 'Bonheur'],
        ['cz' => 'Smutek', 'translation' => 'Tristesse'],
        ['cz' => 'Strach', 'translation' => 'Peur'],
        ['cz' => 'Naděje', 'translation' => 'Espoir'],
        ['cz' => 'Pravda', 'translation' => 'Vérité'],
        ['cz' => 'Lež', 'translation' => 'Mensonge'],
        ['cz' => 'Vzpomínka', 'translation' => 'Souvenir'],
        ['cz' => 'Zkušenost', 'translation' => 'Expérience'],
        ['cz' => 'Důvěra', 'translation' => 'Confiance'],
        ['cz' => 'Vysvětlit', 'translation' => 'Expliquer'],
        ['cz' => 'Souhlasit', 'translation' => 'Accepter'],
        ['cz' => 'Odmítnout', 'translation' => 'Refuser'],
        ['cz' => 'Překvapit', 'translation' => 'Surprendre'],
        ['cz' => 'Zapomenout', 'translation' => 'Oublier'],
        ['cz' => 'Rozhodnout', 'translation' => 'Décider'],
        ['cz' => 'Porovnat', 'translation' => 'Comparer'],
        ['cz' => 'Představit', 'translation' => 'Présenter'],
        ['cz' => 'Dosáhnout', 'translation' => 'Atteindre'],
        ['cz' => 'Pochopit', 'translation' => 'Comprendre'],
        ['cz' => 'Nebezpečný', 'translation' => 'Dangereux'],
        ['cz' => 'Užitečný', 'translation' => 'Utile'],
        ['cz' => 'Nemožný', 'translation' => 'Impossible'],
        ['cz' => 'Spokojený', 'translation' => 'Satisfait'],
        ['cz' => 'Zvědavý', 'translation' => 'Curieux'],
        ['cz' => 'Trpělivý', 'translation' => 'Patient'],
        ['cz' => 'Líný', 'translation' => 'Paresseux'],
        ['cz' => 'Hrdý', 'translation' => 'Fier'],
        ['cz' => 'Samostatný', 'translation' => 'Indépendant'],
        ['cz' => 'Spravedlivý', 'translation' => 'Juste'],
        ['cz' => 'Společnost', 'translation' => 'Société'],
        ['cz' => 'Vláda', 'translation' => 'Gouvernement'],
        ['cz' => 'Zákon', 'translation' => 'Loi'],
        ['cz' => 'Volby', 'translation' => 'Élection'],
        ['cz' => 'Občan', 'translation' => 'Citoyen'],
        ['cz' => 'Plat', 'translation' => 'Salaire'],
        ['cz' => 'Podnik', 'translation' => 'Entreprise'],
        ['cz' => 'Smlouva', 'translation' => 'Contrat'],
        ['cz' => 'Daň', 'translation' => 'Impôt'],
        ['cz' => 'Zaměstnanec', 'translation' => 'Employé'],
        ['cz' => 'Výzkum', 'translation' => 'Recherche'],
        ['cz' => 'Přístroj', 'translation' => 'Appareil'],
        ['cz' => 'Vynález', 'translation' => 'Invention'],
        ['cz' => 'Údaj', 'translation' => 'Donnée'],
        ['cz' => 'Hmota', 'translation' => 'Matière'],
        ['cz' => 'Nemoc', 'translation' => 'Maladie'],
        ['cz' => 'Lék', 'translation' => 'Médicament'],
        ['cz' => 'Bolest', 'translation' => 'Douleur'],
        ['cz' => 'Svaly', 'translation' => 'Muscles'],
        ['cz' => 'Dýchání', 'translation' => 'Respiration'],
        ['cz' => 'Předpokládat', 'translation' => 'Supposer'],
    ],

    'es' => [
        ['cz' => 'Jablko', 'translation' => 'Manzana'],
        ['cz' => 'Hruška', 'translation' => 'Pera'],
        ['cz' => 'Banán', 'translation' => 'Plátano'],
        ['cz' => 'Pomeranč', 'translation' => 'Naranja'],
        ['cz' => 'Citron', 'translation' => 'Limón'],
        ['cz' => 'Pes', 'translation' => 'Perro'],
        ['cz' => 'Kočka', 'translation' => 'Gato'],
        ['cz' => 'Pták', 'translation' => 'Pájaro'],
        ['cz' => 'Ryba', 'translation' => 'Pez'],
        ['cz' => 'Králík', 'translation' => 'Conejo'],

        ['cz' => 'Dům', 'translation' => 'Casa'],
        ['cz' => 'Byt', 'translation' => 'Apartamento'],
        ['cz' => 'Pokoj', 'translation' => 'Habitación'],
        ['cz' => 'Kuchyně', 'translation' => 'Cocina'],
        ['cz' => 'Koupelna', 'translation' => 'Baño'],
        ['cz' => 'Ložnice', 'translation' => 'Dormitorio'],
        ['cz' => 'Obývák', 'translation' => 'Sala de estar'],
        ['cz' => 'Stůl', 'translation' => 'Mesa'],
        ['cz' => 'Židle', 'translation' => 'Silla'],
        ['cz' => 'Postel', 'translation' => 'Cama'],

        ['cz' => 'Kniha', 'translation' => 'Libro'],
        ['cz' => 'Sešit', 'translation' => 'Cuaderno'],
        ['cz' => 'Pero', 'translation' => 'Bolígrafo'],
        ['cz' => 'Tužka', 'translation' => 'Lápiz'],
        ['cz' => 'Papír', 'translation' => 'Papel'],
        ['cz' => 'Guma', 'translation' => 'Goma'],
        ['cz' => 'Škola', 'translation' => 'Escuela'],
        ['cz' => 'Učitel', 'translation' => 'Profesor'],
        ['cz' => 'Student', 'translation' => 'Estudiante'],
        ['cz' => 'Třída', 'translation' => 'Clase'],

        ['cz' => 'Auto', 'translation' => 'Coche'],
        ['cz' => 'Autobus', 'translation' => 'Autobús'],
        ['cz' => 'Vlak', 'translation' => 'Tren'],
        ['cz' => 'Kolo', 'translation' => 'Bicicleta'],
        ['cz' => 'Letadlo', 'translation' => 'Avión'],
        ['cz' => 'Loď', 'translation' => 'Barco'],
        ['cz' => 'Silnice', 'translation' => 'Carretera'],
        ['cz' => 'Most', 'translation' => 'Puente'],
        ['cz' => 'Křižovatka', 'translation' => 'Cruce'],
        ['cz' => 'Semafor', 'translation' => 'Semáforo'],

        ['cz' => 'Voda', 'translation' => 'Agua'],
        ['cz' => 'Vzduch', 'translation' => 'Aire'],
        ['cz' => 'Oheň', 'translation' => 'Fuego'],
        ['cz' => 'Země', 'translation' => 'Tierra'],
        ['cz' => 'Strom', 'translation' => 'Árbol'],
        ['cz' => 'Květina', 'translation' => 'Flor'],
        ['cz' => 'Tráva', 'translation' => 'Césped'],
        ['cz' => 'Řeka', 'translation' => 'Río'],
        ['cz' => 'Jezero', 'translation' => 'Lago'],
        ['cz' => 'Moře', 'translation' => 'Mar'],

        ['cz' => 'Den', 'translation' => 'Día'],
        ['cz' => 'Noc', 'translation' => 'Noche'],
        ['cz' => 'Ráno', 'translation' => 'Mañana'],
        ['cz' => 'Odpoledne', 'translation' => 'Tarde'],
        ['cz' => 'Večer', 'translation' => 'Anochecer'],
        ['cz' => 'Hodina', 'translation' => 'Hora'],
        ['cz' => 'Minuta', 'translation' => 'Minuto'],
        ['cz' => 'Pondělí', 'translation' => 'Lunes'],
        ['cz' => 'Úterý', 'translation' => 'Martes'],
        ['cz' => 'Středa', 'translation' => 'Miércoles'],

        ['cz' => 'Čtvrtek', 'translation' => 'Jueves'],
        ['cz' => 'Pátek', 'translation' => 'Viernes'],
        ['cz' => 'Sobota', 'translation' => 'Sábado'],
        ['cz' => 'Neděle', 'translation' => 'Domingo'],
        ['cz' => 'Muž', 'translation' => 'Hombre'],
        ['cz' => 'Žena', 'translation' => 'Mujer'],
        ['cz' => 'Dítě', 'translation' => 'Niño'],
        ['cz' => 'Rodina', 'translation' => 'Familia'],
        ['cz' => 'Přítel', 'translation' => 'Amigo'],
        ['cz' => 'Doktor', 'translation' => 'Doctor'],
        
        ['cz' => 'Svoboda', 'translation' => 'Libertad'],
        ['cz' => 'Štěstí', 'translation' => 'Felicidad'],
        ['cz' => 'Smutek', 'translation' => 'Tristeza'],
        ['cz' => 'Strach', 'translation' => 'Miedo'],
        ['cz' => 'Naděje', 'translation' => 'Esperanza'],
        ['cz' => 'Pravda', 'translation' => 'Verdad'],
        ['cz' => 'Lež', 'translation' => 'Mentira'],
        ['cz' => 'Vzpomínka', 'translation' => 'Recuerdo'],
        ['cz' => 'Zkušenost', 'translation' => 'Experiencia'],
        ['cz' => 'Důvěra', 'translation' => 'Confianza'],
        ['cz' => 'Vysvětlit', 'translation' => 'Explicar'],
        ['cz' => 'Souhlasit', 'translation' => 'Aceptar'],
        ['cz' => 'Odmítnout', 'translation' => 'Rechazar'],
        ['cz' => 'Překvapit', 'translation' => 'Sorprender'],
        ['cz' => 'Zapomenout', 'translation' => 'Olvidar'],
        ['cz' => 'Rozhodnout', 'translation' => 'Decidir'],
        ['cz' => 'Porovnat', 'translation' => 'Comparar'],
        ['cz' => 'Představit', 'translation' => 'Presentar'],
        ['cz' => 'Dosáhnout', 'translation' => 'Lograr'],
        ['cz' => 'Pochopit', 'translation' => 'Comprender'],
        ['cz' => 'Nebezpečný', 'translation' => 'Peligroso'],
        ['cz' => 'Užitečný', 'translation' => 'Útil'],
        ['cz' => 'Nemožný', 'translation' => 'Imposible'],
        ['cz' => 'Spokojený', 'translation' => 'Satisfecho'],
        ['cz' => 'Zvědavý', 'translation' => 'Curioso'],
        ['cz' => 'Trpělivý', 'translation' => 'Paciente'],
        ['cz' => 'Líný', 'translation' => 'Perezoso'],
        ['cz' => 'Hrdý', 'translation' => 'Orgulloso'],
        ['cz' => 'Samostatný', 'translation' => 'Independiente'],
        ['cz' => 'Spravedlivý', 'translation' => 'Justo'],
        ['cz' => 'Společnost', 'translation' => 'Sociedad'],
        ['cz' => 'Vláda', 'translation' => 'Gobierno'],
        ['cz' => 'Zákon', 'translation' => 'Ley'],
        ['cz' => 'Volby', 'translation' => 'Elección'],
        ['cz' => 'Občan', 'translation' => 'Ciudadano'],
        ['cz' => 'Plat', 'translation' => 'Salario'],
        ['cz' => 'Podnik', 'translation' => 'Empresa'],
        ['cz' => 'Smlouva', 'translation' => 'Contrato'],
        ['cz' => 'Daň', 'translation' => 'Impuesto'],
        ['cz' => 'Zaměstnanec', 'translation' => 'Empleado'],
        ['cz' => 'Výzkum', 'translation' => 'Investigación'],
        ['cz' => 'Přístroj', 'translation' => 'Dispositivo'],
        ['cz' => 'Vynález', 'translation' => 'Invento'],
        ['cz' => 'Údaj', 'translation' => 'Dato'],
        ['cz' => 'Hmota', 'translation' => 'Materia'],
        ['cz' => 'Nemoc', 'translation' => 'Enfermedad'],
        ['cz' => 'Lék', 'translation' => 'Medicamento'],
        ['cz' => 'Bolest', 'translation' => 'Dolor'],
        ['cz' => 'Svaly', 'translation' => 'Músculos'],
        ['cz' => 'Dýchání', 'translation' => 'Respiración'],
        ['cz' => 'Předpokládat', 'translation' => 'Suponer'],
    ],
];
